# -*- coding: utf-8 -*-
"""Machine Learning_K-nearest neighbors (KNN).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VlM5WTu1438OzLRSfdA72iVaOYlacg0z
"""

import matplotlib.pyplot as plt

x = [4, 5, 10, 4, 3, 11, 14 , 8, 10, 12]
y = [21, 19, 24, 17, 16, 25, 24, 22, 21, 21]
classes = [0, 0, 1, 0, 0, 1, 1, 0, 1, 1]

from sklearn.neighbors import KNeighborsClassifier
# KNN algorithm with K=1
data = list(zip(x, y))
#knn = KNeighborsClassifier(n_neighbors=1)
#knn.fit(data, classes)
#new_x = 8
#new_y = 21

#new_point = [(new_x, new_y)]

#prediction = knn.predict(new_point)

#plt.scatter(x + [new_x], y + [new_y], c=classes + [prediction[0]])
#plt.text(x=new_x-1.7, y=new_y-0.7, s=f"new point, class: {prediction[0]}")
#plt.show()



# for higher values ofg K
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(data, classes)
new_x = 8
new_y = 21
new_point = [(new_x, new_y)]
prediction = knn.predict(new_point)

plt.scatter(x + [new_x], y + [new_y], c=classes + [prediction[0]])
plt.text(x=new_x-1.7, y=new_y-0.7, s=f"new point, class: {prediction[0]}")
plt.show()